mutation GenerateRegistrationToken(
  $registrationToken: String
  $registration: TournamentRegistrationInput!
) {
	registerForTournament(
    registrationToken: $registrationToken
    registration: $registration
  ) {
    id
  }
}
